version: '3.7'

services:
  openhab:
    build         : .
    image         : "local/openhab:2.3.0" # TODO: Put version in variable
    container_name: openhab
    restart       : "always"
    network_mode  : bridge

    ports:
      - "8080:8080"
      - "8443:8443"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "addons:/openhab/addons"
      - "conf:/openhab/conf"
      - "userdata:/openhab/userdata"


# uncomment to add devices
#   devices:

      ##
      # Nortek HUSBZB-1 Z-Wave/ZigBee
      #
      # - "/dev/ttyUSB0:/dev/ttyUSB0" # Z-Wave
      # - "/dev/ttyUSB1:/dev/ttyUSB1" # ZigBee

      ##
      # Aeotek Z-Stick Gen5 Z-Wave
      #
      # - "/dev/ttyACM0:/dev/ttyACM0" # Z-Wave

    environment:
      OPENHAB_HTTP_PORT : "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS   : ""

volumes:
  addons:
    driver: local
    name  : openhab_addons
  conf:
    driver: local
    name  : openhab_conf
  userdata:
    driver: local
    name  : openhab_userdata
